import { Question } from '../models/question.model';

export const QUESTION_BANK: Question[] = [

  // ═══════════════════════════════════════════════════════
  // NOUNS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 1, type: 'identify', difficulty: 'easy', wordClass: 'noun',
    sentence: 'The **cat** sat on the mat.',
    highlightedWord: 'cat',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Cat" names an animal — that makes it a noun.' },

  { id: 2, type: 'identify', difficulty: 'easy', wordClass: 'noun',
    sentence: 'She put the **book** on the shelf.',
    highlightedWord: 'book',
    options: ['Noun', 'Verb', 'Adjective', 'Preposition'],
    correctAnswer: 'Noun',
    explanation: '"Book" names a thing, so it is a noun.' },

  { id: 3, type: 'identify', difficulty: 'easy', wordClass: 'noun',
    sentence: 'The **teacher** wrote on the board.',
    highlightedWord: 'teacher',
    options: ['Noun', 'Verb', 'Adverb', 'Adjective'],
    correctAnswer: 'Noun',
    explanation: '"Teacher" names a person — it is a common noun.' },

  { id: 4, type: 'identify', difficulty: 'easy', wordClass: 'noun',
    sentence: '**London** is the capital of England.',
    highlightedWord: 'London',
    options: ['Noun', 'Adjective', 'Pronoun', 'Determiner'],
    correctAnswer: 'Noun',
    explanation: '"London" is a proper noun — it names a specific place.' },

  { id: 5, type: 'classify', difficulty: 'easy', wordClass: 'noun',
    sentence: 'Which of these words is a noun?',
    options: ['dog', 'run', 'quickly', 'under'],
    correctAnswer: 'dog',
    explanation: '"Dog" names an animal (a thing), making it a noun.' },

  { id: 6, type: 'fill-blank', difficulty: 'easy', wordClass: 'noun',
    sentence: 'The ___ barked loudly all night.',
    options: ['dog', 'quickly', 'under', 'happy'],
    correctAnswer: 'dog',
    explanation: '"Dog" is a noun naming the subject of the sentence.' },

  { id: 7, type: 'identify', difficulty: 'easy', wordClass: 'noun',
    sentence: 'We visited the **museum** on Saturday.',
    highlightedWord: 'museum',
    options: ['Noun', 'Verb', 'Preposition', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Museum" is a common noun naming a place.' },

  { id: 8, type: 'identify', difficulty: 'easy', wordClass: 'noun',
    sentence: 'The **team** celebrated their victory.',
    highlightedWord: 'team',
    options: ['Noun', 'Verb', 'Pronoun', 'Adjective'],
    correctAnswer: 'Noun',
    explanation: '"Team" is a collective noun naming a group of people.' },

  // Medium
  { id: 9, type: 'identify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'Her **courage** impressed everyone in the room.',
    highlightedWord: 'courage',
    options: ['Noun', 'Adjective', 'Verb', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Courage" is an abstract noun — it names a quality or idea, even though you cannot touch it.' },

  { id: 10, type: 'identify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'The **evidence** pointed to a different conclusion.',
    highlightedWord: 'evidence',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Evidence" is an abstract noun naming a concept.' },

  { id: 11, type: 'classify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'Which of these is an abstract noun?',
    options: ['justice', 'table', 'London', 'swim'],
    correctAnswer: 'justice',
    explanation: '"Justice" is an abstract noun — it names an idea you cannot see or touch.' },

  { id: 12, type: 'identify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'His **childhood** was spent in the countryside.',
    highlightedWord: 'childhood',
    options: ['Noun', 'Adjective', 'Verb', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Childhood" is an abstract noun naming a period of time and experience.' },

  { id: 13, type: 'fill-blank', difficulty: 'medium', wordClass: 'noun',
    sentence: 'The ___ of the old house had faded over the years.',
    options: ['beauty', 'beautifully', 'beautiful', 'beautify'],
    correctAnswer: 'beauty',
    explanation: '"Beauty" is a noun (abstract) and is the subject of this clause.' },

  { id: 14, type: 'identify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'The **government** announced new plans today.',
    highlightedWord: 'government',
    options: ['Noun', 'Verb', 'Adjective', 'Conjunction'],
    correctAnswer: 'Noun',
    explanation: '"Government" is a collective noun naming an organisation.' },

  { id: 15, type: 'classify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'Which of these words is a noun?',
    options: ['happiness', 'quickly', 'under', 'beautiful'],
    correctAnswer: 'happiness',
    explanation: '"Happiness" is an abstract noun naming a feeling.' },

  { id: 16, type: 'identify', difficulty: 'medium', wordClass: 'noun',
    sentence: 'There was a long **silence** after her speech.',
    highlightedWord: 'silence',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Silence" is an abstract noun naming a condition (the absence of sound).' },

  { id: 17, type: 'fill-blank', difficulty: 'medium', wordClass: 'noun',
    sentence: 'The ___ of the volcano shook the whole island.',
    options: ['eruption', 'erupting', 'erupt', 'erupted'],
    correctAnswer: 'eruption',
    explanation: '"Eruption" is a noun — it is the subject of the verb "shook".' },

  // Hard
  { id: 18, type: 'identify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'She went for a **run** before breakfast.',
    highlightedWord: 'run',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Run" is used as a noun here (preceded by "a"), not as a verb. The same word can belong to different classes depending on how it is used.' },

  { id: 19, type: 'identify', difficulty: 'hard', wordClass: 'noun',
    sentence: '**Swimming** is her favourite sport.',
    highlightedWord: 'Swimming',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Swimming" is a gerund here — a verb form acting as a noun (it is the subject of "is").' },

  { id: 20, type: 'classify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'In which sentence is "light" used as a noun?',
    options: ['Turn on the light.', 'The bag is light.', 'She will light the candle.', 'He moved at a light pace.'],
    correctAnswer: 'Turn on the light.',
    explanation: 'In "Turn on the light", "light" is a noun (an object). In the others it is an adjective or a verb.' },

  { id: 21, type: 'identify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'The **reading** of the will took place at noon.',
    highlightedWord: 'reading',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Reading" acts as a noun here — it is preceded by "the" and is the subject of the clause.' },

  { id: 22, type: 'identify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'There was a sharp **drop** in temperature overnight.',
    highlightedWord: 'drop',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"Drop" is a noun here (preceded by "a"), meaning a decrease. It can also be a verb, but not in this sentence.' },

  { id: 23, type: 'identify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'The **unknown** held both fear and excitement for them.',
    highlightedWord: 'unknown',
    options: ['Noun', 'Adjective', 'Verb', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"The unknown" is a nominalised adjective — "unknown" is normally an adjective, but here it is used as a noun phrase.' },

  { id: 24, type: 'fill-blank', difficulty: 'hard', wordClass: 'noun',
    sentence: 'The ___ of the new bridge took three years.',
    options: ['construction', 'construct', 'constructing', 'constructed'],
    correctAnswer: 'construction',
    explanation: '"Construction" is a noun (preceded by "the") and fits as the subject of "took".' },

  { id: 25, type: 'classify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'Which word is used as a noun in: "The poor need more support"?',
    options: ['poor', 'need', 'more', 'support'],
    correctAnswer: 'poor',
    explanation: '"The poor" uses an adjective as a noun (nominalisation) — it refers to a group of people.' },

  // ═══════════════════════════════════════════════════════
  // VERBS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 26, type: 'identify', difficulty: 'easy', wordClass: 'verb',
    sentence: 'She **ran** quickly across the field.',
    highlightedWord: 'ran',
    options: ['Verb', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Verb',
    explanation: '"Ran" is a verb — it describes the action of running.' },

  { id: 27, type: 'identify', difficulty: 'easy', wordClass: 'verb',
    sentence: 'The dog **jumped** over the fence.',
    highlightedWord: 'jumped',
    options: ['Verb', 'Noun', 'Adjective', 'Preposition'],
    correctAnswer: 'Verb',
    explanation: '"Jumped" is a verb describing an action.' },

  { id: 28, type: 'classify', difficulty: 'easy', wordClass: 'verb',
    sentence: 'Which of these words is a verb?',
    options: ['dance', 'happy', 'quickly', 'table'],
    correctAnswer: 'dance',
    explanation: '"Dance" is a verb — it describes an action you can perform.' },

  { id: 29, type: 'fill-blank', difficulty: 'easy', wordClass: 'verb',
    sentence: 'The children ___ in the playground all afternoon.',
    options: ['played', 'happy', 'quickly', 'the'],
    correctAnswer: 'played',
    explanation: '"Played" is a verb telling us what the children did.' },

  { id: 30, type: 'identify', difficulty: 'easy', wordClass: 'verb',
    sentence: 'We **ate** pizza for dinner last night.',
    highlightedWord: 'ate',
    options: ['Verb', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Verb',
    explanation: '"Ate" is a verb describing the action of eating.' },

  { id: 31, type: 'identify', difficulty: 'easy', wordClass: 'verb',
    sentence: 'She **smiled** when she heard the news.',
    highlightedWord: 'smiled',
    options: ['Verb', 'Noun', 'Adverb', 'Conjunction'],
    correctAnswer: 'Verb',
    explanation: '"Smiled" is an action verb.' },

  { id: 32, type: 'fill-blank', difficulty: 'easy', wordClass: 'verb',
    sentence: 'The dog ___ its tail excitedly.',
    options: ['wagged', 'happy', 'some', 'behind'],
    correctAnswer: 'wagged',
    explanation: '"Wagged" is a verb — it tells us what action the dog performed.' },

  { id: 33, type: 'identify', difficulty: 'easy', wordClass: 'verb',
    sentence: 'They **sing** in the school choir every week.',
    highlightedWord: 'sing',
    options: ['Verb', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Verb',
    explanation: '"Sing" is a verb describing an action.' },

  // Medium
  { id: 34, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'The flowers **are** blooming in the garden.',
    highlightedWord: 'are',
    options: ['Verb', 'Noun', 'Conjunction', 'Determiner'],
    correctAnswer: 'Verb',
    explanation: '"Are" is an auxiliary (helping) verb that works with "blooming" to form the present continuous tense.' },

  { id: 35, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'They **might** come to the party later.',
    highlightedWord: 'might',
    options: ['Verb', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Verb',
    explanation: '"Might" is a modal verb — a special type of verb that shows possibility.' },

  { id: 36, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'She **seems** very confident today.',
    highlightedWord: 'seems',
    options: ['Verb', 'Adverb', 'Adjective', 'Noun'],
    correctAnswer: 'Verb',
    explanation: '"Seems" is a linking verb — it connects the subject to a description.' },

  { id: 37, type: 'classify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'Which of these words is a verb?',
    options: ['whispered', 'gentle', 'the', 'above'],
    correctAnswer: 'whispered',
    explanation: '"Whispered" is a verb — it describes the action of speaking quietly.' },

  { id: 38, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'The children **were** playing in the park.',
    highlightedWord: 'were',
    options: ['Verb', 'Pronoun', 'Conjunction', 'Preposition'],
    correctAnswer: 'Verb',
    explanation: '"Were" is an auxiliary verb helping to form the past continuous tense.' },

  { id: 39, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'You **should** finish your homework before dinner.',
    highlightedWord: 'should',
    options: ['Verb', 'Noun', 'Adverb', 'Conjunction'],
    correctAnswer: 'Verb',
    explanation: '"Should" is a modal verb showing obligation or advice.' },

  { id: 40, type: 'fill-blank', difficulty: 'medium', wordClass: 'verb',
    sentence: 'He ___ been waiting for over an hour.',
    options: ['had', 'his', 'quickly', 'some'],
    correctAnswer: 'had',
    explanation: '"Had" is an auxiliary verb used here to form the past perfect tense.' },

  { id: 41, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'The bridge **appears** safe to cross.',
    highlightedWord: 'appears',
    options: ['Verb', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Verb',
    explanation: '"Appears" is a linking verb connecting the subject to the description "safe".' },

  { id: 42, type: 'identify', difficulty: 'medium', wordClass: 'verb',
    sentence: 'She **must** be at the station by now.',
    highlightedWord: 'must',
    options: ['Verb', 'Noun', 'Adverb', 'Determiner'],
    correctAnswer: 'Verb',
    explanation: '"Must" is a modal verb showing certainty or strong obligation.' },

  // Hard
  { id: 43, type: 'identify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'The children **have** finished their work.',
    highlightedWord: 'have',
    options: ['Verb', 'Noun', 'Pronoun', 'Determiner'],
    correctAnswer: 'Verb',
    explanation: '"Have" is an auxiliary verb here, forming the present perfect tense with "finished".' },

  { id: 44, type: 'classify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'In which sentence is "light" used as a verb?',
    options: ['She will light the candle.', 'Turn on the light.', 'The bag is light.', 'He moved at a light pace.'],
    correctAnswer: 'She will light the candle.',
    explanation: 'Only in "She will light the candle" is "light" a verb — it describes an action. In the others it is a noun or adjective.' },

  { id: 45, type: 'identify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'The report **was written** by the head teacher.',
    highlightedWord: 'was written',
    options: ['Verb', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Verb',
    explanation: '"Was written" is a passive verb — it is formed with an auxiliary verb (was) and a past participle (written).' },

  { id: 46, type: 'identify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'I **dare** you to try it.',
    highlightedWord: 'dare',
    options: ['Verb', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Verb',
    explanation: '"Dare" is used as a main verb here expressing a challenge.' },

  { id: 47, type: 'classify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'Which word is a verb in: "He had a long run this morning"?',
    options: ['had', 'run', 'long', 'morning'],
    correctAnswer: 'had',
    explanation: '"Had" is the verb (past tense of "have"). "Run" looks like a verb but here it is a noun (preceded by "a").' },

  { id: 48, type: 'identify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'She **is** very talented.',
    highlightedWord: 'is',
    options: ['Verb', 'Adjective', 'Pronoun', 'Conjunction'],
    correctAnswer: 'Verb',
    explanation: '"Is" is a linking verb (a form of "be"). It links the subject to the adjective "talented".' },

  { id: 49, type: 'fill-blank', difficulty: 'hard', wordClass: 'verb',
    sentence: 'The painting ___ completed in just two days.',
    options: ['was', 'very', 'some', 'the'],
    correctAnswer: 'was',
    explanation: '"Was" is an auxiliary verb forming the passive voice with "completed".' },

  { id: 50, type: 'identify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'He **used to** walk to school every day.',
    highlightedWord: 'used to',
    options: ['Verb', 'Preposition', 'Adverb', 'Conjunction'],
    correctAnswer: 'Verb',
    explanation: '"Used to" is a semi-modal verb describing a past habit.' },

  // ═══════════════════════════════════════════════════════
  // ADJECTIVES
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 51, type: 'identify', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'The **big** dog barked at the postman.',
    highlightedWord: 'big',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Big" describes the noun "dog", so it is an adjective.' },

  { id: 52, type: 'identify', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'She wore a **red** hat to the parade.',
    highlightedWord: 'red',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Red" describes the noun "hat" — it is an adjective.' },

  { id: 53, type: 'classify', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'Which of these words is an adjective?',
    options: ['happy', 'run', 'quickly', 'and'],
    correctAnswer: 'happy',
    explanation: '"Happy" describes how a person feels — it is an adjective.' },

  { id: 54, type: 'fill-blank', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'The ___ puppy wagged its tail.',
    options: ['tiny', 'swiftly', 'although', 'some'],
    correctAnswer: 'tiny',
    explanation: '"Tiny" is an adjective describing the noun "puppy".' },

  { id: 55, type: 'identify', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'It was a **cold** and windy morning.',
    highlightedWord: 'cold',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Cold" describes the noun "morning" — it is an adjective.' },

  { id: 56, type: 'identify', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'The **enormous** elephant walked through the jungle.',
    highlightedWord: 'enormous',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Enormous" describes the noun "elephant" — it is an adjective.' },

  { id: 57, type: 'fill-blank', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'He gave a ___ answer in the test.',
    options: ['brilliant', 'brilliantly', 'brilliance', 'to brilliance'],
    correctAnswer: 'brilliant',
    explanation: '"Brilliant" is an adjective describing the answer.' },

  { id: 58, type: 'identify', difficulty: 'easy', wordClass: 'adjective',
    sentence: 'She lives in a **tall** tower by the sea.',
    highlightedWord: 'tall',
    options: ['Adjective', 'Noun', 'Adverb', 'Conjunction'],
    correctAnswer: 'Adjective',
    explanation: '"Tall" describes the noun "tower" — it is an adjective.' },

  // Medium
  { id: 59, type: 'identify', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'The **ancient** castle stood on top of the hill.',
    highlightedWord: 'ancient',
    options: ['Adjective', 'Noun', 'Adverb', 'Verb'],
    correctAnswer: 'Adjective',
    explanation: '"Ancient" is an adjective describing the age of the castle.' },

  { id: 60, type: 'identify', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'She wore a **sparkling** dress to the ball.',
    highlightedWord: 'sparkling',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Sparkling" is used as an adjective here — it describes the dress.' },

  { id: 61, type: 'classify', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'Which of these words is an adjective?',
    options: ['delicious', 'quickly', 'they', 'walked'],
    correctAnswer: 'delicious',
    explanation: '"Delicious" is an adjective describing how food tastes.' },

  { id: 62, type: 'identify', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'The **exhausted** runner crossed the finish line.',
    highlightedWord: 'exhausted',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Exhausted" is an adjective here describing how the runner feels.' },

  { id: 63, type: 'fill-blank', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'The ___ sunset painted the sky with colour.',
    options: ['vivid', 'vividly', 'vividness', 'vivifying'],
    correctAnswer: 'vivid',
    explanation: '"Vivid" is an adjective describing the sunset.' },

  { id: 64, type: 'identify', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'It was a **mysterious** letter with no return address.',
    highlightedWord: 'mysterious',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Mysterious" is an adjective describing the letter.' },

  { id: 65, type: 'identify', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'The water was **freezing** cold.',
    highlightedWord: 'freezing',
    options: ['Adjective', 'Verb', 'Noun', 'Preposition'],
    correctAnswer: 'Adjective',
    explanation: '"Freezing" is used as an adjective here, describing how cold the water is.' },

  { id: 66, type: 'fill-blank', difficulty: 'medium', wordClass: 'adjective',
    sentence: 'The ___ house at the end of the street had been empty for years.',
    options: ['abandoned', 'abandon', 'abandonment', 'to abandon'],
    correctAnswer: 'abandoned',
    explanation: '"Abandoned" is a past-participle adjective describing the house.' },

  // Hard
  { id: 67, type: 'identify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'He walked at a **fast** pace.',
    highlightedWord: 'fast',
    options: ['Adjective', 'Adverb', 'Verb', 'Noun'],
    correctAnswer: 'Adjective',
    explanation: '"Fast" describes the noun "pace" here, making it an adjective. (It can also be an adverb, e.g. "he ran fast".)' },

  { id: 68, type: 'classify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'In which sentence is "present" used as an adjective?',
    options: ['All students present must sign in.', 'She opened her present.', 'I present this award to you.', 'She is always present in spirit.'],
    correctAnswer: 'All students present must sign in.',
    explanation: 'In "All students present must sign in", "present" is a postpositive adjective (placed after the noun) meaning "here/attending".' },

  { id: 69, type: 'identify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'The **broken** window let in the cold air.',
    highlightedWord: 'broken',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Broken" is a past-participle adjective here — it describes the noun "window".' },

  { id: 70, type: 'identify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'He sat in the **left** seat.',
    highlightedWord: 'left',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Left" is used as an adjective here — it tells us which seat (the one on the left side).' },

  { id: 71, type: 'classify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'In "The light bag was easy to carry", what word class is "light"?',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Light" describes the bag (it is not heavy), so it functions as an adjective.' },

  { id: 72, type: 'identify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'She felt **content** after finishing the meal.',
    highlightedWord: 'content',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Content" is a predicative adjective here — it follows the linking verb "felt" and describes the subject.' },

  { id: 73, type: 'fill-blank', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'The results were ___, far better than expected.',
    options: ['staggering', 'staggeringly', 'stagger', 'staggered'],
    correctAnswer: 'staggering',
    explanation: '"Staggering" is a predicative adjective following the linking verb "were".' },

  { id: 74, type: 'identify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'The door was **open**.',
    highlightedWord: 'open',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Open" is a predicative adjective here — it describes the state of the door after the linking verb "was".' },

  // ═══════════════════════════════════════════════════════
  // ADVERBS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 75, type: 'identify', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'The tortoise moved **slowly** across the road.',
    highlightedWord: 'slowly',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Slowly" is an adverb — it tells us how the tortoise moved (modifying the verb).' },

  { id: 76, type: 'identify', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'She **always** remembers to bring her books.',
    highlightedWord: 'always',
    options: ['Adverb', 'Adjective', 'Conjunction', 'Pronoun'],
    correctAnswer: 'Adverb',
    explanation: '"Always" is an adverb of frequency telling us how often something happens.' },

  { id: 77, type: 'classify', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'Which of these words is an adverb?',
    options: ['quickly', 'happy', 'table', 'the'],
    correctAnswer: 'quickly',
    explanation: '"Quickly" is an adverb describing how an action is done.' },

  { id: 78, type: 'fill-blank', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'The children sang ___ during the concert.',
    options: ['beautifully', 'beautiful', 'some', 'they'],
    correctAnswer: 'beautifully',
    explanation: '"Beautifully" is an adverb — it describes how the children sang.' },

  { id: 79, type: 'identify', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'He **never** eats vegetables.',
    highlightedWord: 'never',
    options: ['Adverb', 'Adjective', 'Verb', 'Noun'],
    correctAnswer: 'Adverb',
    explanation: '"Never" is an adverb of frequency.' },

  { id: 80, type: 'identify', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'The music played **softly** in the background.',
    highlightedWord: 'softly',
    options: ['Adverb', 'Adjective', 'Noun', 'Conjunction'],
    correctAnswer: 'Adverb',
    explanation: '"Softly" is an adverb telling us how the music played.' },

  { id: 81, type: 'fill-blank', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'She finished the test ___ and handed it in.',
    options: ['quickly', 'quick', 'quickness', 'a quick'],
    correctAnswer: 'quickly',
    explanation: '"Quickly" is an adverb describing how she finished.' },

  { id: 82, type: 'identify', difficulty: 'easy', wordClass: 'adverb',
    sentence: 'They arrived **early** for the show.',
    highlightedWord: 'early',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Early" is an adverb of time telling us when they arrived.' },

  // Medium
  { id: 83, type: 'identify', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'He **almost** missed the bus this morning.',
    highlightedWord: 'almost',
    options: ['Adverb', 'Adjective', 'Verb', 'Preposition'],
    correctAnswer: 'Adverb',
    explanation: '"Almost" is an adverb modifying the verb "missed" — it tells us the degree to which he missed the bus.' },

  { id: 84, type: 'identify', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'The weather was **extremely** cold yesterday.',
    highlightedWord: 'extremely',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Extremely" is an adverb modifying the adjective "cold" — it tells us the degree.' },

  { id: 85, type: 'identify', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'She **still** hadn\'t finished when the bell rang.',
    highlightedWord: 'still',
    options: ['Adverb', 'Adjective', 'Verb', 'Conjunction'],
    correctAnswer: 'Adverb',
    explanation: '"Still" is an adverb of time showing that the action was ongoing.' },

  { id: 86, type: 'classify', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'Which of these words is an adverb?',
    options: ['perhaps', 'beauty', 'and', 'the'],
    correctAnswer: 'perhaps',
    explanation: '"Perhaps" is an adverb of possibility — it modifies the whole statement.' },

  { id: 87, type: 'fill-blank', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'She could ___ reach the top shelf.',
    options: ['hardly', 'hard', 'hardness', 'a hard'],
    correctAnswer: 'hardly',
    explanation: '"Hardly" is an adverb meaning "barely" — it modifies the verb "reach".' },

  { id: 88, type: 'identify', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'He had **already** eaten by the time we arrived.',
    highlightedWord: 'already',
    options: ['Adverb', 'Adjective', 'Conjunction', 'Preposition'],
    correctAnswer: 'Adverb',
    explanation: '"Already" is an adverb of time.' },

  { id: 89, type: 'identify', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'The old man sat **quietly** on the bench.',
    highlightedWord: 'quietly',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Quietly" is an adverb describing how the man sat.' },

  { id: 90, type: 'fill-blank', difficulty: 'medium', wordClass: 'adverb',
    sentence: 'The answer was ___ what we had expected.',
    options: ['exactly', 'exact', 'exactness', 'exactful'],
    correctAnswer: 'exactly',
    explanation: '"Exactly" is an adverb emphasising the precision of the match.' },

  // Hard
  { id: 91, type: 'identify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'He could **not** believe what had happened.',
    highlightedWord: 'not',
    options: ['Adverb', 'Conjunction', 'Preposition', 'Determiner'],
    correctAnswer: 'Adverb',
    explanation: '"Not" is an adverb — it negates the verb "believe".' },

  { id: 92, type: 'classify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'In "She runs fast", what word class is "fast"?',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Fast" here modifies the verb "runs", so it is an adverb. (In "a fast runner" it would be an adjective.)' },

  { id: 93, type: 'identify', difficulty: 'hard', wordClass: 'adverb',
    sentence: '**Frankly**, I think the plan needs more work.',
    highlightedWord: 'Frankly',
    options: ['Adverb', 'Adjective', 'Conjunction', 'Noun'],
    correctAnswer: 'Adverb',
    explanation: '"Frankly" is a sentence adverb — it modifies the entire statement, not just a single word.' },

  { id: 94, type: 'classify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'In "She works hard", what word class is "hard"?',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Hard" modifies the verb "works", so it is an adverb. Note: "hardly" has a different meaning (barely).' },

  { id: 95, type: 'identify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'The cake is good **enough** to enter the competition.',
    highlightedWord: 'enough',
    options: ['Adverb', 'Determiner', 'Adjective', 'Noun'],
    correctAnswer: 'Adverb',
    explanation: '"Enough" is an adverb here — it modifies the adjective "good". (It can also be a determiner, e.g. "enough cake".)' },

  { id: 96, type: 'identify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'She **just** wanted to help.',
    highlightedWord: 'just',
    options: ['Adverb', 'Adjective', 'Conjunction', 'Verb'],
    correctAnswer: 'Adverb',
    explanation: '"Just" is an adverb here emphasising the simplicity of her intention.' },

  { id: 97, type: 'classify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'In "He is well today", what word class is "well"?',
    options: ['Adjective', 'Adverb', 'Noun', 'Verb'],
    correctAnswer: 'Adjective',
    explanation: 'After a linking verb ("is"), "well" functions as an adjective describing the subject\'s health. When it modifies a verb (e.g. "he plays well"), it is an adverb.' },

  { id: 98, type: 'fill-blank', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'Is she here ___? I thought she had left.',
    options: ['still', 'always', 'never', 'yet'],
    correctAnswer: 'still',
    explanation: '"Still" is an adverb of time showing the action is ongoing/continuing.' },

  // ═══════════════════════════════════════════════════════
  // PRONOUNS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 99, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: '**She** went to the shop to buy some milk.',
    highlightedWord: 'She',
    options: ['Pronoun', 'Noun', 'Determiner', 'Verb'],
    correctAnswer: 'Pronoun',
    explanation: '"She" is a pronoun — it replaces the name of a female person.' },

  { id: 100, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: '**We** enjoyed the trip to the seaside.',
    highlightedWord: 'We',
    options: ['Pronoun', 'Determiner', 'Noun', 'Conjunction'],
    correctAnswer: 'Pronoun',
    explanation: '"We" is a personal pronoun standing in place of a group of people.' },

  { id: 101, type: 'classify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: 'Which of these words is a pronoun?',
    options: ['he', 'happy', 'under', 'quickly'],
    correctAnswer: 'he',
    explanation: '"He" is a pronoun used in place of a male person\'s name.' },

  { id: 102, type: 'fill-blank', difficulty: 'easy', wordClass: 'pronoun',
    sentence: '___ forgot to bring an umbrella today.',
    options: ['He', 'The', 'Quickly', 'Happy'],
    correctAnswer: 'He',
    explanation: '"He" is a pronoun acting as the subject of the sentence.' },

  { id: 103, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: '**They** are my best friends.',
    highlightedWord: 'They',
    options: ['Pronoun', 'Noun', 'Determiner', 'Verb'],
    correctAnswer: 'Pronoun',
    explanation: '"They" is a personal pronoun replacing the names of a group of people.' },

  { id: 104, type: 'fill-blank', difficulty: 'easy', wordClass: 'pronoun',
    sentence: 'I gave ___ a birthday card.',
    options: ['her', 'happy', 'quickly', 'the'],
    correctAnswer: 'her',
    explanation: '"Her" is an object pronoun replacing a female person\'s name.' },

  { id: 105, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: 'Can **you** help me carry these bags?',
    highlightedWord: 'you',
    options: ['Pronoun', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Pronoun',
    explanation: '"You" is a personal pronoun used to address someone directly.' },

  { id: 106, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: '**It** was raining heavily outside.',
    highlightedWord: 'It',
    options: ['Pronoun', 'Noun', 'Determiner', 'Verb'],
    correctAnswer: 'Pronoun',
    explanation: '"It" is a pronoun used as an impersonal subject (referring to the weather).' },

  // Medium
  { id: 107, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'The book is **mine** and I want it back.',
    highlightedWord: 'mine',
    options: ['Pronoun', 'Noun', 'Adjective', 'Determiner'],
    correctAnswer: 'Pronoun',
    explanation: '"Mine" is a possessive pronoun — it shows ownership without being followed by a noun.' },

  { id: 108, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'The cake was made by **herself**.',
    highlightedWord: 'herself',
    options: ['Pronoun', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Pronoun',
    explanation: '"Herself" is a reflexive pronoun — it refers back to the subject.' },

  { id: 109, type: 'classify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'Which of these words is a pronoun?',
    options: ['them', 'quickly', 'under', 'happy'],
    correctAnswer: 'them',
    explanation: '"Them" is an object pronoun used in place of naming specific people or things.' },

  { id: 110, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: '**Nobody** knew the answer to the question.',
    highlightedWord: 'Nobody',
    options: ['Pronoun', 'Noun', 'Determiner', 'Adverb'],
    correctAnswer: 'Pronoun',
    explanation: '"Nobody" is an indefinite pronoun — it refers to no person.' },

  { id: 111, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: '**Everyone** clapped at the end of the show.',
    highlightedWord: 'Everyone',
    options: ['Pronoun', 'Noun', 'Determiner', 'Conjunction'],
    correctAnswer: 'Pronoun',
    explanation: '"Everyone" is an indefinite pronoun — it refers to all people.' },

  { id: 112, type: 'fill-blank', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'The prize is ___ — you won it fair and square.',
    options: ['yours', 'your', 'you', 'yourself'],
    correctAnswer: 'yours',
    explanation: '"Yours" is a possessive pronoun — it stands alone without being followed by a noun.' },

  { id: 113, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: '**Both** were late for the meeting.',
    highlightedWord: 'Both',
    options: ['Pronoun', 'Determiner', 'Noun', 'Adjective'],
    correctAnswer: 'Pronoun',
    explanation: '"Both" is an indefinite pronoun here — it refers to two people without naming them.' },

  { id: 114, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'Is there **anything** I can do to help?',
    highlightedWord: 'anything',
    options: ['Pronoun', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Pronoun',
    explanation: '"Anything" is an indefinite pronoun — it refers to an unspecified thing.' },

  // Hard
  { id: 115, type: 'identify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'This is the house **that** Jack built.',
    highlightedWord: 'that',
    options: ['Pronoun', 'Determiner', 'Conjunction', 'Adverb'],
    correctAnswer: 'Pronoun',
    explanation: '"That" is a relative pronoun here — it introduces the relative clause and refers back to "house".' },

  { id: 116, type: 'classify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'In which sentence is "this" used as a pronoun (not a determiner)?',
    options: ['This is what I mean.', 'This book is mine.', 'This car is fast.', 'This weather is dreadful.'],
    correctAnswer: 'This is what I mean.',
    explanation: 'In "This is what I mean", "this" stands alone as the subject — it is a pronoun. In the others, "this" is followed by a noun, making it a determiner.' },

  { id: 117, type: 'identify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'The girl **whom** I met yesterday was very kind.',
    highlightedWord: 'whom',
    options: ['Pronoun', 'Determiner', 'Conjunction', 'Preposition'],
    correctAnswer: 'Pronoun',
    explanation: '"Whom" is a relative pronoun — the object form of "who".' },

  { id: 118, type: 'identify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: '**One** should always be honest.',
    highlightedWord: 'One',
    options: ['Pronoun', 'Determiner', 'Noun', 'Adjective'],
    correctAnswer: 'Pronoun',
    explanation: '"One" is an indefinite pronoun — it refers to people in general.' },

  { id: 119, type: 'classify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'In "None of the answers were correct", what word class is "none"?',
    options: ['Pronoun', 'Determiner', 'Adjective', 'Noun'],
    correctAnswer: 'Pronoun',
    explanation: '"None" is an indefinite pronoun meaning "not one" — it stands in place of "not one of the answers".' },

  { id: 120, type: 'identify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'The children entertained **themselves** for hours.',
    highlightedWord: 'themselves',
    options: ['Pronoun', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Pronoun',
    explanation: '"Themselves" is a reflexive pronoun — the object refers back to the subject "children".' },

  { id: 121, type: 'identify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: '**What** surprised me most was her patience.',
    highlightedWord: 'What',
    options: ['Pronoun', 'Determiner', 'Conjunction', 'Adverb'],
    correctAnswer: 'Pronoun',
    explanation: '"What" is a relative pronoun here — it introduces a noun clause and acts as the subject.' },

  { id: 122, type: 'fill-blank', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'The winner surprised ___ with an incredible speech.',
    options: ['us', 'our', 'ours', 'ourselves'],
    correctAnswer: 'us',
    explanation: '"Us" is an object pronoun — it is the object of the verb "surprised".' },

  // ═══════════════════════════════════════════════════════
  // PREPOSITIONS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 123, type: 'identify', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'The cat hid **under** the table.',
    highlightedWord: 'under',
    options: ['Preposition', 'Adverb', 'Noun', 'Conjunction'],
    correctAnswer: 'Preposition',
    explanation: '"Under" is a preposition — it shows the position of the cat relative to the table.' },

  { id: 124, type: 'identify', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'She sat **on** the chair.',
    highlightedWord: 'on',
    options: ['Preposition', 'Adverb', 'Verb', 'Conjunction'],
    correctAnswer: 'Preposition',
    explanation: '"On" is a preposition showing position.' },

  { id: 125, type: 'classify', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'Which of these words is a preposition?',
    options: ['at', 'happy', 'run', 'quickly'],
    correctAnswer: 'at',
    explanation: '"At" is a preposition showing a relationship in time or place.' },

  { id: 126, type: 'fill-blank', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'The bird sat ___ the branch and sang.',
    options: ['on', 'quickly', 'beautiful', 'and'],
    correctAnswer: 'on',
    explanation: '"On" is a preposition showing where the bird sat.' },

  { id: 127, type: 'identify', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'The dog is **in** the garden.',
    highlightedWord: 'in',
    options: ['Preposition', 'Adverb', 'Verb', 'Noun'],
    correctAnswer: 'Preposition',
    explanation: '"In" is a preposition showing where the dog is.' },

  { id: 128, type: 'identify', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'She walked **to** the park.',
    highlightedWord: 'to',
    options: ['Preposition', 'Adverb', 'Verb', 'Conjunction'],
    correctAnswer: 'Preposition',
    explanation: '"To" is a preposition showing direction of movement.' },

  { id: 129, type: 'fill-blank', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'He jumped ___ the puddle.',
    options: ['over', 'quickly', 'happy', 'and'],
    correctAnswer: 'over',
    explanation: '"Over" is a preposition showing direction of movement.' },

  { id: 130, type: 'identify', difficulty: 'easy', wordClass: 'preposition',
    sentence: 'The book is **beside** the lamp.',
    highlightedWord: 'beside',
    options: ['Preposition', 'Adjective', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Beside" is a preposition showing position.' },

  // Medium
  { id: 131, type: 'identify', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'We walked **through** the forest.',
    highlightedWord: 'through',
    options: ['Preposition', 'Verb', 'Adverb', 'Adjective'],
    correctAnswer: 'Preposition',
    explanation: '"Through" is a preposition showing direction of movement.' },

  { id: 132, type: 'classify', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'Which of these words is a preposition?',
    options: ['between', 'quickly', 'happy', 'jumped'],
    correctAnswer: 'between',
    explanation: '"Between" is a preposition showing a positional relationship.' },

  { id: 133, type: 'identify', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'We drove **across** the bridge at sunset.',
    highlightedWord: 'across',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Across" is a preposition showing direction.' },

  { id: 134, type: 'identify', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'She arrived **before** everyone else.',
    highlightedWord: 'before',
    options: ['Preposition', 'Conjunction', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Before" is a preposition here — followed by the noun phrase "everyone else" to show a time relationship.' },

  { id: 135, type: 'fill-blank', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'The treasure was hidden ___ the two large rocks.',
    options: ['between', 'quickly', 'beautiful', 'and'],
    correctAnswer: 'between',
    explanation: '"Between" is a preposition showing position relative to the two rocks.' },

  { id: 136, type: 'identify', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'The town is **towards** the north of the county.',
    highlightedWord: 'towards',
    options: ['Preposition', 'Adverb', 'Adjective', 'Conjunction'],
    correctAnswer: 'Preposition',
    explanation: '"Towards" is a preposition showing direction.' },

  { id: 137, type: 'identify', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'She did it **despite** feeling unwell.',
    highlightedWord: 'despite',
    options: ['Preposition', 'Conjunction', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Despite" is a preposition — followed by a noun phrase "feeling unwell" (not a clause), showing contrast.' },

  { id: 138, type: 'fill-blank', difficulty: 'medium', wordClass: 'preposition',
    sentence: 'He hid the letter ___ the floorboards.',
    options: ['beneath', 'because', 'beautifully', 'but'],
    correctAnswer: 'beneath',
    explanation: '"Beneath" is a preposition of place.' },

  // Hard
  { id: 139, type: 'classify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'In "She has lived here since 2010", what word class is "since"?',
    options: ['Preposition', 'Conjunction', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Since" is a preposition here, followed by the noun phrase "2010". When followed by a clause, "since" is a conjunction.' },

  { id: 140, type: 'classify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'In which sentence is "like" used as a preposition?',
    options: ['She swims like a fish.', 'I like swimming.', 'She gave a like on the photo.', 'The children like cake.'],
    correctAnswer: 'She swims like a fish.',
    explanation: 'In "She swims like a fish", "like" is a preposition meaning "in the manner of". In the others it is a verb or noun.' },

  { id: 141, type: 'identify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'The soldiers marched **past** the palace.',
    highlightedWord: 'past',
    options: ['Preposition', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Past" is a preposition here showing movement alongside/beyond the palace.' },

  { id: 142, type: 'identify', difficulty: 'hard', wordClass: 'preposition',
    sentence: '**Following** the announcement, there was silence.',
    highlightedWord: 'Following',
    options: ['Preposition', 'Verb', 'Adjective', 'Conjunction'],
    correctAnswer: 'Preposition',
    explanation: '"Following" is used as a preposition here meaning "after" — it is followed by a noun phrase, not a clause.' },

  { id: 143, type: 'classify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'In "He ran after the bus", what word class is "after"?',
    options: ['Preposition', 'Conjunction', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"After" is a preposition here, followed by the noun phrase "the bus". (When followed by a clause, "after" is a conjunction.)' },

  { id: 144, type: 'identify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'The trophy sat **atop** the bookcase.',
    highlightedWord: 'atop',
    options: ['Preposition', 'Adverb', 'Adjective', 'Noun'],
    correctAnswer: 'Preposition',
    explanation: '"Atop" is a formal preposition meaning "on top of".' },

  { id: 145, type: 'fill-blank', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'She spoke ___ behalf of the entire class.',
    options: ['on', 'and', 'although', 'always'],
    correctAnswer: 'on',
    explanation: '"On behalf of" is a complex preposition meaning "representing".' },

  { id: 146, type: 'identify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'He arrived home **after** a long journey through the mountains.',
    highlightedWord: 'after',
    options: ['Preposition', 'Conjunction', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"After" is a preposition here — it is followed by a noun phrase ("a long journey"), not a clause.' },

  // ═══════════════════════════════════════════════════════
  // CONJUNCTIONS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 147, type: 'identify', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'I like apples **and** oranges.',
    highlightedWord: 'and',
    options: ['Conjunction', 'Preposition', 'Noun', 'Verb'],
    correctAnswer: 'Conjunction',
    explanation: '"And" is a coordinating conjunction joining two nouns.' },

  { id: 148, type: 'identify', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'He wanted to go outside **but** it was raining.',
    highlightedWord: 'but',
    options: ['Conjunction', 'Preposition', 'Noun', 'Adverb'],
    correctAnswer: 'Conjunction',
    explanation: '"But" is a coordinating conjunction showing contrast.' },

  { id: 149, type: 'classify', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'Which of these words is a conjunction?',
    options: ['and', 'quickly', 'happy', 'under'],
    correctAnswer: 'and',
    explanation: '"And" is a conjunction that joins words or clauses.' },

  { id: 150, type: 'fill-blank', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'We can go to the park ___ stay at home.',
    options: ['or', 'quickly', 'beautiful', 'the'],
    correctAnswer: 'or',
    explanation: '"Or" is a coordinating conjunction offering a choice.' },

  { id: 151, type: 'identify', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'She was tired **because** she had been running.',
    highlightedWord: 'because',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Pronoun'],
    correctAnswer: 'Conjunction',
    explanation: '"Because" is a subordinating conjunction explaining the reason.' },

  { id: 152, type: 'fill-blank', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'I will come to the party ___ I finish my homework first.',
    options: ['if', 'slowly', 'happy', 'under'],
    correctAnswer: 'if',
    explanation: '"If" is a subordinating conjunction showing a condition.' },

  { id: 153, type: 'identify', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'She sang **and** danced all evening.',
    highlightedWord: 'and',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Noun'],
    correctAnswer: 'Conjunction',
    explanation: '"And" is a coordinating conjunction joining two verbs.' },

  { id: 154, type: 'identify', difficulty: 'easy', wordClass: 'conjunction',
    sentence: 'He played outside **when** it stopped raining.',
    highlightedWord: 'when',
    options: ['Conjunction', 'Adverb', 'Preposition', 'Pronoun'],
    correctAnswer: 'Conjunction',
    explanation: '"When" is a subordinating conjunction showing time.' },

  // Medium
  { id: 155, type: 'identify', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'She read **while** he cooked dinner.',
    highlightedWord: 'while',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Noun'],
    correctAnswer: 'Conjunction',
    explanation: '"While" is a subordinating conjunction showing two events happening at the same time.' },

  { id: 156, type: 'classify', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'Which of these words is a conjunction?',
    options: ['although', 'slowly', 'table', 'the'],
    correctAnswer: 'although',
    explanation: '"Although" is a subordinating conjunction introducing a contrasting idea.' },

  { id: 157, type: 'identify', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'You can\'t go out **unless** you tidy your room.',
    highlightedWord: 'unless',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Noun'],
    correctAnswer: 'Conjunction',
    explanation: '"Unless" is a subordinating conjunction expressing a negative condition.' },

  { id: 158, type: 'identify', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'She kept going **until** she finished the race.',
    highlightedWord: 'until',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Verb'],
    correctAnswer: 'Conjunction',
    explanation: '"Until" is a subordinating conjunction of time here (followed by a clause).' },

  { id: 159, type: 'fill-blank', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'He smiled ___ he was clearly upset.',
    options: ['although', 'slowly', 'the', 'never'],
    correctAnswer: 'although',
    explanation: '"Although" is a subordinating conjunction introducing a contrast.' },

  { id: 160, type: 'identify', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'I like English **whereas** my brother prefers maths.',
    highlightedWord: 'whereas',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Noun'],
    correctAnswer: 'Conjunction',
    explanation: '"Whereas" is a subordinating conjunction showing contrast.' },

  { id: 161, type: 'identify', difficulty: 'medium', wordClass: 'conjunction',
    sentence: '**Neither** the cake nor the biscuits were left.',
    highlightedWord: 'Neither',
    options: ['Conjunction', 'Determiner', 'Pronoun', 'Noun'],
    correctAnswer: 'Conjunction',
    explanation: '"Neither...nor" is a correlative conjunction pair joining two negative options.' },

  { id: 162, type: 'fill-blank', difficulty: 'medium', wordClass: 'conjunction',
    sentence: 'He was nervous ___ he stepped onto the stage.',
    options: ['as', 'the', 'quickly', 'never'],
    correctAnswer: 'as',
    explanation: '"As" is a subordinating conjunction of time.' },

  // Hard
  { id: 163, type: 'classify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'In "She has lived here since she was a child", what word class is "since"?',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Verb'],
    correctAnswer: 'Conjunction',
    explanation: '"Since" is a subordinating conjunction here — it introduces the clause "she was a child". When followed by a noun phrase, "since" is a preposition.' },

  { id: 164, type: 'classify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'In "She left after the lesson ended", what word class is "after"?',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Verb'],
    correctAnswer: 'Conjunction',
    explanation: '"After" is a subordinating conjunction here — it introduces the clause "the lesson ended".' },

  { id: 165, type: 'identify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'She worked hard **so that** she could pass the exam.',
    highlightedWord: 'so that',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Determiner'],
    correctAnswer: 'Conjunction',
    explanation: '"So that" is a multi-word subordinating conjunction expressing purpose.' },

  { id: 166, type: 'classify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'In which sentence is "as" used as a conjunction?',
    options: ['As she walked in, everyone turned.', 'She dressed as a witch.', 'He works as a teacher.', 'She is as tall as him.'],
    correctAnswer: 'As she walked in, everyone turned.',
    explanation: '"As" introduces a clause in "As she walked in" — that makes it a subordinating conjunction.' },

  { id: 167, type: 'identify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'He is talented **yet** he never practises.',
    highlightedWord: 'yet',
    options: ['Conjunction', 'Adverb', 'Preposition', 'Noun'],
    correctAnswer: 'Conjunction',
    explanation: '"Yet" is a coordinating conjunction here meaning "but" — it shows contrast.' },

  { id: 168, type: 'identify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'She will succeed **provided that** she works hard.',
    highlightedWord: 'provided that',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Verb'],
    correctAnswer: 'Conjunction',
    explanation: '"Provided that" is a complex subordinating conjunction expressing a condition.' },

  { id: 169, type: 'identify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: 'He is clever, **for** he has read widely.',
    highlightedWord: 'for',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Determiner'],
    correctAnswer: 'Conjunction',
    explanation: '"For" is used here as a coordinating conjunction (similar to "because") introducing a reason. This is a formal, literary usage.' },

  { id: 170, type: 'identify', difficulty: 'hard', wordClass: 'conjunction',
    sentence: '**Not only** did she win, but she also broke the record.',
    highlightedWord: 'Not only',
    options: ['Conjunction', 'Adverb', 'Pronoun', 'Preposition'],
    correctAnswer: 'Conjunction',
    explanation: '"Not only...but" is a correlative conjunction pair used for emphasis.' },

  // ═══════════════════════════════════════════════════════
  // DETERMINERS
  // ═══════════════════════════════════════════════════════

  // Easy
  { id: 171, type: 'identify', difficulty: 'easy', wordClass: 'determiner',
    sentence: '**The** children played in the park.',
    highlightedWord: 'The',
    options: ['Determiner', 'Noun', 'Pronoun', 'Adjective'],
    correctAnswer: 'Determiner',
    explanation: '"The" is a determiner (definite article) — it introduces the noun "children".' },

  { id: 172, type: 'identify', difficulty: 'easy', wordClass: 'determiner',
    sentence: 'I saw **a** bird in the garden.',
    highlightedWord: 'a',
    options: ['Determiner', 'Pronoun', 'Preposition', 'Adjective'],
    correctAnswer: 'Determiner',
    explanation: '"A" is a determiner (indefinite article) introducing the noun "bird".' },

  { id: 173, type: 'classify', difficulty: 'easy', wordClass: 'determiner',
    sentence: 'Which of these words is a determiner?',
    options: ['the', 'slowly', 'jumped', 'happy'],
    correctAnswer: 'the',
    explanation: '"The" is a determiner — it introduces a noun.' },

  { id: 174, type: 'fill-blank', difficulty: 'easy', wordClass: 'determiner',
    sentence: 'I want ___ apple, please.',
    options: ['an', 'quickly', 'running', 'behind'],
    correctAnswer: 'an',
    explanation: '"An" is the indefinite article used before nouns starting with a vowel sound.' },

  { id: 175, type: 'identify', difficulty: 'easy', wordClass: 'determiner',
    sentence: '**My** dog loves chasing squirrels.',
    highlightedWord: 'My',
    options: ['Determiner', 'Pronoun', 'Noun', 'Adjective'],
    correctAnswer: 'Determiner',
    explanation: '"My" is a possessive determiner — it introduces the noun "dog" and shows ownership.' },

  { id: 176, type: 'identify', difficulty: 'easy', wordClass: 'determiner',
    sentence: '**This** book is really exciting.',
    highlightedWord: 'This',
    options: ['Determiner', 'Pronoun', 'Adjective', 'Noun'],
    correctAnswer: 'Determiner',
    explanation: '"This" is a demonstrative determiner — it points to the specific noun "book".' },

  { id: 177, type: 'fill-blank', difficulty: 'easy', wordClass: 'determiner',
    sentence: 'Could I have ___ more water, please?',
    options: ['some', 'quickly', 'running', 'happy'],
    correctAnswer: 'some',
    explanation: '"Some" is a determiner indicating an unspecified quantity.' },

  { id: 178, type: 'identify', difficulty: 'easy', wordClass: 'determiner',
    sentence: '**Those** shoes are far too expensive.',
    highlightedWord: 'Those',
    options: ['Determiner', 'Pronoun', 'Adjective', 'Noun'],
    correctAnswer: 'Determiner',
    explanation: '"Those" is a demonstrative determiner pointing to specific shoes.' },

  // Medium
  { id: 179, type: 'identify', difficulty: 'medium', wordClass: 'determiner',
    sentence: '**Some** people prefer tea over coffee.',
    highlightedWord: 'Some',
    options: ['Determiner', 'Pronoun', 'Adjective', 'Adverb'],
    correctAnswer: 'Determiner',
    explanation: '"Some" is a determiner — it tells us about the quantity of the noun "people".' },

  { id: 180, type: 'identify', difficulty: 'medium', wordClass: 'determiner',
    sentence: '**Every** student must complete the task.',
    highlightedWord: 'Every',
    options: ['Determiner', 'Adjective', 'Pronoun', 'Adverb'],
    correctAnswer: 'Determiner',
    explanation: '"Every" is a determiner specifying that all students are included.' },

  { id: 181, type: 'classify', difficulty: 'medium', wordClass: 'determiner',
    sentence: 'Which of these words is a determiner?',
    options: ['an', 'slowly', 'jumped', 'happy'],
    correctAnswer: 'an',
    explanation: '"An" is a determiner (indefinite article) used before nouns starting with a vowel sound.' },

  { id: 182, type: 'identify', difficulty: 'medium', wordClass: 'determiner',
    sentence: 'I ate **three** biscuits after lunch.',
    highlightedWord: 'three',
    options: ['Determiner', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Determiner',
    explanation: '"Three" is a determiner (a number) telling us how many biscuits.' },

  { id: 183, type: 'identify', difficulty: 'medium', wordClass: 'determiner',
    sentence: '**Both** players were given a yellow card.',
    highlightedWord: 'Both',
    options: ['Determiner', 'Pronoun', 'Conjunction', 'Noun'],
    correctAnswer: 'Determiner',
    explanation: '"Both" is a determiner here — it precedes the noun "players" and refers to the two of them.' },

  { id: 184, type: 'fill-blank', difficulty: 'medium', wordClass: 'determiner',
    sentence: '___ dog in the garden belongs to our neighbour.',
    options: ['That', 'Quickly', 'Running', 'Behind'],
    correctAnswer: 'That',
    explanation: '"That" is a demonstrative determiner pointing to the specific dog.' },

  { id: 185, type: 'identify', difficulty: 'medium', wordClass: 'determiner',
    sentence: '**Several** children were absent from school today.',
    highlightedWord: 'Several',
    options: ['Determiner', 'Adjective', 'Pronoun', 'Adverb'],
    correctAnswer: 'Determiner',
    explanation: '"Several" is a determiner indicating an unspecified but more-than-two quantity.' },

  { id: 186, type: 'identify', difficulty: 'medium', wordClass: 'determiner',
    sentence: 'She has read **enough** books to know the answer.',
    highlightedWord: 'enough',
    options: ['Determiner', 'Adverb', 'Adjective', 'Pronoun'],
    correctAnswer: 'Determiner',
    explanation: '"Enough" is a determiner here — it precedes the noun "books" to indicate a sufficient quantity.' },

  // Hard
  { id: 187, type: 'classify', difficulty: 'hard', wordClass: 'determiner',
    sentence: 'In which sentence is "this" used as a determiner (not a pronoun)?',
    options: ['This book is mine.', 'This is my favourite film.', 'This is what I told you.', 'This will never work.'],
    correctAnswer: 'This book is mine.',
    explanation: '"This" is a determiner when it precedes a noun (e.g. "this book"). When it stands alone as the subject or object, it is a pronoun.' },

  { id: 188, type: 'identify', difficulty: 'hard', wordClass: 'determiner',
    sentence: '**No** tickets were available for the concert.',
    highlightedWord: 'No',
    options: ['Determiner', 'Adverb', 'Adjective', 'Conjunction'],
    correctAnswer: 'Determiner',
    explanation: '"No" is a determiner indicating zero quantity before the noun "tickets".' },

  { id: 189, type: 'classify', difficulty: 'hard', wordClass: 'determiner',
    sentence: 'In "Which car do you prefer?", what word class is "which"?',
    options: ['Determiner', 'Pronoun', 'Conjunction', 'Adjective'],
    correctAnswer: 'Determiner',
    explanation: '"Which" is an interrogative determiner here — it precedes the noun "car". When it stands alone, it is a pronoun.' },

  { id: 190, type: 'identify', difficulty: 'hard', wordClass: 'determiner',
    sentence: '**Whose** umbrella is this?',
    highlightedWord: 'Whose',
    options: ['Determiner', 'Pronoun', 'Adjective', 'Conjunction'],
    correctAnswer: 'Determiner',
    explanation: '"Whose" is an interrogative determiner — it precedes the noun "umbrella" to ask about ownership.' },

  { id: 191, type: 'identify', difficulty: 'hard', wordClass: 'determiner',
    sentence: '**What** noise are they making upstairs?',
    highlightedWord: 'What',
    options: ['Determiner', 'Pronoun', 'Adverb', 'Conjunction'],
    correctAnswer: 'Determiner',
    explanation: '"What" is an interrogative determiner here — it introduces the noun "noise". (Compare: "What are they doing?" where "what" is a pronoun.)' },

  { id: 192, type: 'classify', difficulty: 'hard', wordClass: 'determiner',
    sentence: 'In "Both are correct", what word class is "both"?',
    options: ['Pronoun', 'Determiner', 'Conjunction', 'Adjective'],
    correctAnswer: 'Pronoun',
    explanation: '"Both" stands alone as the subject — it is a pronoun. Compare with "Both answers are correct" where "both" precedes a noun and is a determiner.' },

  { id: 193, type: 'fill-blank', difficulty: 'hard', wordClass: 'determiner',
    sentence: 'She had ___ idea what was about to happen.',
    options: ['no', 'not', 'never', 'none'],
    correctAnswer: 'no',
    explanation: '"No" is a determiner preceding the noun "idea" to indicate zero quantity.' },

  { id: 194, type: 'identify', difficulty: 'hard', wordClass: 'determiner',
    sentence: 'She is **such** a talented musician.',
    highlightedWord: 'such',
    options: ['Determiner', 'Adjective', 'Adverb', 'Pronoun'],
    correctAnswer: 'Determiner',
    explanation: '"Such" is a predeterminer here — it comes before the article "a" to add emphasis.' },

  // ═══════════════════════════════════════════════════════
  // EXTRA TRICKY MIXED QUESTIONS
  // ═══════════════════════════════════════════════════════

  { id: 195, type: 'classify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'In "She is a very good singer", what word class is "very"?',
    options: ['Adverb', 'Adjective', 'Determiner', 'Conjunction'],
    correctAnswer: 'Adverb',
    explanation: '"Very" is an adverb of degree — it modifies the adjective "good".' },

  { id: 196, type: 'identify', difficulty: 'hard', wordClass: 'verb',
    sentence: 'He **needs** to practise more.',
    highlightedWord: 'needs',
    options: ['Verb', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Verb',
    explanation: '"Needs" is a main verb here. It requires "to + infinitive" unlike modal verbs.' },

  { id: 197, type: 'classify', difficulty: 'hard', wordClass: 'noun',
    sentence: 'In "The accused was found guilty", what word class is "accused"?',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    explanation: '"The accused" is a nominalised past participle — "accused" functions as a noun (the person on trial).' },

  { id: 198, type: 'classify', difficulty: 'hard', wordClass: 'adverb',
    sentence: 'In "That is an extremely difficult question", what word class is "extremely"?',
    options: ['Adverb', 'Adjective', 'Determiner', 'Noun'],
    correctAnswer: 'Adverb',
    explanation: '"Extremely" is an adverb modifying the adjective "difficult".' },

  { id: 199, type: 'identify', difficulty: 'hard', wordClass: 'preposition',
    sentence: 'She stood **apart from** the rest of the group.',
    highlightedWord: 'apart from',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Verb'],
    correctAnswer: 'Preposition',
    explanation: '"Apart from" is a complex preposition meaning "separate from" or "besides".' },

  { id: 200, type: 'classify', difficulty: 'hard', wordClass: 'adjective',
    sentence: 'In "The sleeping child looked peaceful", what word class is "sleeping"?',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    explanation: '"Sleeping" is a present-participle adjective here — it describes the noun "child".' },

  // ═══════════════════════════════════════════════════════
  // POSSESSIVE PRONOUNS (extra focused set)
  // ═══════════════════════════════════════════════════════

  { id: 201, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: 'That bag is **hers**.',
    highlightedWord: 'hers',
    options: ['Pronoun', 'Determiner', 'Noun', 'Adjective'],
    correctAnswer: 'Pronoun',
    explanation: '"Hers" is a possessive pronoun — it stands alone and shows the bag belongs to her. There is no noun after it.' },

  { id: 202, type: 'identify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: 'The blue coat is **theirs**.',
    highlightedWord: 'theirs',
    options: ['Pronoun', 'Determiner', 'Adjective', 'Noun'],
    correctAnswer: 'Pronoun',
    explanation: '"Theirs" is a possessive pronoun — it replaces "their coat" and stands alone.' },

  { id: 203, type: 'classify', difficulty: 'easy', wordClass: 'pronoun',
    sentence: 'Which of these is a possessive pronoun?',
    options: ['ours', 'our', 'we', 'us'],
    correctAnswer: 'ours',
    explanation: '"Ours" is a possessive pronoun — it stands alone to show ownership. "Our" is a possessive determiner (it must be followed by a noun).' },

  { id: 204, type: 'classify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'In which sentence is a possessive PRONOUN used (not a possessive determiner)?',
    options: ['The decision is theirs to make.', 'Their decision surprised us.', 'Their team won the match.', 'Their garden looks lovely.'],
    correctAnswer: 'The decision is theirs to make.',
    explanation: '"Theirs" stands alone after the verb — it is a possessive pronoun. In the other sentences, "their" comes before a noun, making it a possessive determiner.' },

  { id: 205, type: 'identify', difficulty: 'medium', wordClass: 'pronoun',
    sentence: 'I forgot my pencil — can I borrow **yours**?',
    highlightedWord: 'yours',
    options: ['Pronoun', 'Determiner', 'Adjective', 'Noun'],
    correctAnswer: 'Pronoun',
    explanation: '"Yours" is a possessive pronoun — it stands in place of "your pencil" without repeating the noun.' },

  { id: 206, type: 'classify', difficulty: 'hard', wordClass: 'pronoun',
    sentence: 'What is the difference between "her book" and "hers"?',
    options: ['"her" is a determiner; "hers" is a pronoun', '"her" is a pronoun; "hers" is a determiner', 'Both are pronouns', 'Both are determiners'],
    correctAnswer: '"her" is a determiner; "hers" is a pronoun',
    explanation: '"Her" comes before a noun ("her book") so it is a possessive determiner. "Hers" stands alone ("the book is hers") so it is a possessive pronoun.' },
];
