import { Question } from '../models/question.model';

export const QUESTION_BANK: Question[] = [
  // ── NOUNS ──────────────────────────────────────────────
  {
    id: 1,
    type: 'identify',
    sentence: 'The **cat** sat on the mat.',
    highlightedWord: 'cat',
    options: ['Noun', 'Verb', 'Adjective', 'Adverb'],
    correctAnswer: 'Noun',
    wordClass: 'noun',
    explanation: '"Cat" is a noun because it names an animal (a thing).',
  },
  {
    id: 2,
    type: 'identify',
    sentence: 'Her **courage** impressed everyone in the room.',
    highlightedWord: 'courage',
    options: ['Noun', 'Adjective', 'Verb', 'Adverb'],
    correctAnswer: 'Noun',
    wordClass: 'noun',
    explanation: '"Courage" is an abstract noun — it names a quality or idea.',
  },
  {
    id: 3,
    type: 'identify',
    sentence: '**London** is the capital of England.',
    highlightedWord: 'London',
    options: ['Noun', 'Adjective', 'Pronoun', 'Determiner'],
    correctAnswer: 'Noun',
    wordClass: 'noun',
    explanation: '"London" is a proper noun — it names a specific place.',
  },
  {
    id: 4,
    type: 'classify',
    sentence: 'Which of these words is a noun?',
    options: ['happiness', 'quickly', 'under', 'beautiful'],
    correctAnswer: 'happiness',
    wordClass: 'noun',
    explanation: '"Happiness" is an abstract noun naming a feeling. "Quickly" is an adverb, "under" is a preposition and "beautiful" is an adjective.',
  },
  {
    id: 5,
    type: 'identify',
    sentence: 'The **team** celebrated their victory.',
    highlightedWord: 'team',
    options: ['Noun', 'Verb', 'Pronoun', 'Adjective'],
    correctAnswer: 'Noun',
    wordClass: 'noun',
    explanation: '"Team" is a collective noun — it names a group.',
  },
  {
    id: 6,
    type: 'fill-blank',
    sentence: 'The ___ played in the garden all afternoon.',
    options: ['children', 'quickly', 'under', 'beautiful'],
    correctAnswer: 'children',
    wordClass: 'noun',
    explanation: '"Children" is a noun and fits as the subject of the sentence.',
  },
  {
    id: 7,
    type: 'identify',
    sentence: 'We visited the **museum** on Saturday.',
    highlightedWord: 'museum',
    options: ['Noun', 'Verb', 'Preposition', 'Adverb'],
    correctAnswer: 'Noun',
    wordClass: 'noun',
    explanation: '"Museum" is a common noun naming a place.',
  },

  // ── VERBS ──────────────────────────────────────────────
  {
    id: 8,
    type: 'identify',
    sentence: 'She **ran** quickly across the field.',
    highlightedWord: 'ran',
    options: ['Verb', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Verb',
    wordClass: 'verb',
    explanation: '"Ran" is a verb because it describes an action.',
  },
  {
    id: 9,
    type: 'identify',
    sentence: 'The flowers **are** blooming in the garden.',
    highlightedWord: 'are',
    options: ['Verb', 'Noun', 'Conjunction', 'Determiner'],
    correctAnswer: 'Verb',
    wordClass: 'verb',
    explanation: '"Are" is an auxiliary (helping) verb used with "blooming".',
  },
  {
    id: 10,
    type: 'identify',
    sentence: 'You **should** finish your homework before dinner.',
    highlightedWord: 'should',
    options: ['Verb', 'Noun', 'Adverb', 'Conjunction'],
    correctAnswer: 'Verb',
    wordClass: 'verb',
    explanation: '"Should" is a modal verb — it shows possibility or obligation.',
  },
  {
    id: 11,
    type: 'classify',
    sentence: 'Which of these words is a verb?',
    options: ['whispered', 'gentle', 'the', 'above'],
    correctAnswer: 'whispered',
    wordClass: 'verb',
    explanation: '"Whispered" is a verb describing an action (speaking quietly).',
  },
  {
    id: 12,
    type: 'fill-blank',
    sentence: 'The dog ___ its tail excitedly.',
    options: ['wagged', 'happy', 'some', 'behind'],
    correctAnswer: 'wagged',
    wordClass: 'verb',
    explanation: '"Wagged" is a verb — it tells us the action the dog performed.',
  },
  {
    id: 13,
    type: 'identify',
    sentence: 'They **might** come to the party later.',
    highlightedWord: 'might',
    options: ['Verb', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Verb',
    wordClass: 'verb',
    explanation: '"Might" is a modal verb showing possibility.',
  },
  {
    id: 14,
    type: 'identify',
    sentence: 'The children **were** playing in the park.',
    highlightedWord: 'were',
    options: ['Verb', 'Pronoun', 'Conjunction', 'Preposition'],
    correctAnswer: 'Verb',
    wordClass: 'verb',
    explanation: '"Were" is an auxiliary verb helping to form the past continuous tense.',
  },

  // ── ADJECTIVES ─────────────────────────────────────────
  {
    id: 15,
    type: 'identify',
    sentence: 'The **enormous** elephant walked through the jungle.',
    highlightedWord: 'enormous',
    options: ['Adjective', 'Noun', 'Verb', 'Adverb'],
    correctAnswer: 'Adjective',
    wordClass: 'adjective',
    explanation: '"Enormous" is an adjective because it describes the noun "elephant".',
  },
  {
    id: 16,
    type: 'identify',
    sentence: 'She wore a **sparkling** dress to the ball.',
    highlightedWord: 'sparkling',
    options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
    correctAnswer: 'Adjective',
    wordClass: 'adjective',
    explanation: '"Sparkling" is an adjective here — it describes the dress.',
  },
  {
    id: 17,
    type: 'classify',
    sentence: 'Which of these words is an adjective?',
    options: ['delicious', 'quickly', 'they', 'walked'],
    correctAnswer: 'delicious',
    wordClass: 'adjective',
    explanation: '"Delicious" is an adjective that describes how food tastes.',
  },
  {
    id: 18,
    type: 'fill-blank',
    sentence: 'The ___ sunset painted the sky with colour.',
    options: ['beautiful', 'ran', 'because', 'they'],
    correctAnswer: 'beautiful',
    wordClass: 'adjective',
    explanation: '"Beautiful" is an adjective describing the sunset.',
  },
  {
    id: 19,
    type: 'identify',
    sentence: 'The water was **freezing** cold.',
    highlightedWord: 'freezing',
    options: ['Adjective', 'Verb', 'Noun', 'Preposition'],
    correctAnswer: 'Adjective',
    wordClass: 'adjective',
    explanation: '"Freezing" is used as an adjective here to describe how cold the water was.',
  },
  {
    id: 20,
    type: 'identify',
    sentence: 'He gave a **brilliant** answer in the test.',
    highlightedWord: 'brilliant',
    options: ['Adjective', 'Noun', 'Adverb', 'Verb'],
    correctAnswer: 'Adjective',
    wordClass: 'adjective',
    explanation: '"Brilliant" is an adjective describing the answer.',
  },

  // ── ADVERBS ────────────────────────────────────────────
  {
    id: 21,
    type: 'identify',
    sentence: 'The tortoise moved **slowly** across the road.',
    highlightedWord: 'slowly',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Slowly" is an adverb because it describes how the tortoise moved (the verb).',
  },
  {
    id: 22,
    type: 'identify',
    sentence: 'She **always** remembers to bring her books.',
    highlightedWord: 'always',
    options: ['Adverb', 'Adjective', 'Conjunction', 'Pronoun'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Always" is an adverb of frequency — it tells us how often.',
  },
  {
    id: 23,
    type: 'classify',
    sentence: 'Which of these words is an adverb?',
    options: ['carefully', 'happy', 'table', 'the'],
    correctAnswer: 'carefully',
    wordClass: 'adverb',
    explanation: '"Carefully" is an adverb — it describes how an action is done.',
  },
  {
    id: 24,
    type: 'fill-blank',
    sentence: 'The children sang ___ during the concert.',
    options: ['beautifully', 'beautiful', 'some', 'they'],
    correctAnswer: 'beautifully',
    wordClass: 'adverb',
    explanation: '"Beautifully" is an adverb describing how the children sang.',
  },
  {
    id: 25,
    type: 'identify',
    sentence: 'He **almost** missed the bus this morning.',
    highlightedWord: 'almost',
    options: ['Adverb', 'Adjective', 'Verb', 'Preposition'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Almost" is an adverb modifying the verb "missed".',
  },
  {
    id: 26,
    type: 'identify',
    sentence: 'The music played **softly** in the background.',
    highlightedWord: 'softly',
    options: ['Adverb', 'Adjective', 'Noun', 'Conjunction'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Softly" is an adverb telling us how the music played.',
  },

  // ── PRONOUNS ───────────────────────────────────────────
  {
    id: 27,
    type: 'identify',
    sentence: '**She** went to the shop to buy some milk.',
    highlightedWord: 'She',
    options: ['Pronoun', 'Noun', 'Determiner', 'Verb'],
    correctAnswer: 'Pronoun',
    wordClass: 'pronoun',
    explanation: '"She" is a pronoun — it replaces the name of a person.',
  },
  {
    id: 28,
    type: 'identify',
    sentence: 'The book is **mine** and I want it back.',
    highlightedWord: 'mine',
    options: ['Pronoun', 'Noun', 'Adjective', 'Determiner'],
    correctAnswer: 'Pronoun',
    wordClass: 'pronoun',
    explanation: '"Mine" is a possessive pronoun — it shows ownership.',
  },
  {
    id: 29,
    type: 'classify',
    sentence: 'Which of these words is a pronoun?',
    options: ['them', 'quickly', 'under', 'happy'],
    correctAnswer: 'them',
    wordClass: 'pronoun',
    explanation: '"Them" is a pronoun used in place of naming specific people or things.',
  },
  {
    id: 30,
    type: 'fill-blank',
    sentence: '___ forgot to bring an umbrella today.',
    options: ['He', 'The', 'Quickly', 'Happy'],
    correctAnswer: 'He',
    wordClass: 'pronoun',
    explanation: '"He" is a pronoun that acts as the subject of the sentence.',
  },
  {
    id: 31,
    type: 'identify',
    sentence: 'The cake was made by **herself**.',
    highlightedWord: 'herself',
    options: ['Pronoun', 'Noun', 'Adverb', 'Adjective'],
    correctAnswer: 'Pronoun',
    wordClass: 'pronoun',
    explanation: '"Herself" is a reflexive pronoun referring back to the subject.',
  },
  {
    id: 32,
    type: 'identify',
    sentence: '**Nobody** knew the answer to the question.',
    highlightedWord: 'Nobody',
    options: ['Pronoun', 'Noun', 'Determiner', 'Adverb'],
    correctAnswer: 'Pronoun',
    wordClass: 'pronoun',
    explanation: '"Nobody" is an indefinite pronoun — it refers to no person.',
  },

  // ── PREPOSITIONS ───────────────────────────────────────
  {
    id: 33,
    type: 'identify',
    sentence: 'The cat hid **under** the table.',
    highlightedWord: 'under',
    options: ['Preposition', 'Adverb', 'Noun', 'Conjunction'],
    correctAnswer: 'Preposition',
    wordClass: 'preposition',
    explanation: '"Under" is a preposition showing the position of the cat relative to the table.',
  },
  {
    id: 34,
    type: 'identify',
    sentence: 'We walked **through** the forest.',
    highlightedWord: 'through',
    options: ['Preposition', 'Verb', 'Adverb', 'Adjective'],
    correctAnswer: 'Preposition',
    wordClass: 'preposition',
    explanation: '"Through" is a preposition showing direction of movement.',
  },
  {
    id: 35,
    type: 'classify',
    sentence: 'Which of these words is a preposition?',
    options: ['between', 'quickly', 'happy', 'jumped'],
    correctAnswer: 'between',
    wordClass: 'preposition',
    explanation: '"Between" is a preposition showing position or relationship.',
  },
  {
    id: 36,
    type: 'fill-blank',
    sentence: 'The bird sat ___ the branch and sang.',
    options: ['on', 'quickly', 'beautiful', 'and'],
    correctAnswer: 'on',
    wordClass: 'preposition',
    explanation: '"On" is a preposition showing where the bird sat.',
  },
  {
    id: 37,
    type: 'identify',
    sentence: 'The shop is **beside** the library.',
    highlightedWord: 'beside',
    options: ['Preposition', 'Noun', 'Adverb', 'Conjunction'],
    correctAnswer: 'Preposition',
    wordClass: 'preposition',
    explanation: '"Beside" is a preposition showing the shop\'s position relative to the library.',
  },
  {
    id: 38,
    type: 'identify',
    sentence: 'She arrived **before** everyone else.',
    highlightedWord: 'before',
    options: ['Preposition', 'Conjunction', 'Adverb', 'Verb'],
    correctAnswer: 'Preposition',
    wordClass: 'preposition',
    explanation: '"Before" is a preposition here showing a time relationship.',
  },

  // ── CONJUNCTIONS ───────────────────────────────────────
  {
    id: 39,
    type: 'identify',
    sentence: 'I like apples **and** oranges.',
    highlightedWord: 'and',
    options: ['Conjunction', 'Preposition', 'Noun', 'Verb'],
    correctAnswer: 'Conjunction',
    wordClass: 'conjunction',
    explanation: '"And" is a coordinating conjunction joining two nouns.',
  },
  {
    id: 40,
    type: 'identify',
    sentence: 'She was tired **because** she had been running.',
    highlightedWord: 'because',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Pronoun'],
    correctAnswer: 'Conjunction',
    wordClass: 'conjunction',
    explanation: '"Because" is a subordinating conjunction — it explains the reason.',
  },
  {
    id: 41,
    type: 'identify',
    sentence: 'He wanted to go outside **but** it was raining.',
    highlightedWord: 'but',
    options: ['Conjunction', 'Preposition', 'Noun', 'Adverb'],
    correctAnswer: 'Conjunction',
    wordClass: 'conjunction',
    explanation: '"But" is a coordinating conjunction showing contrast.',
  },
  {
    id: 42,
    type: 'classify',
    sentence: 'Which of these words is a conjunction?',
    options: ['although', 'slowly', 'table', 'the'],
    correctAnswer: 'although',
    wordClass: 'conjunction',
    explanation: '"Although" is a subordinating conjunction introducing a contrasting idea.',
  },
  {
    id: 43,
    type: 'fill-blank',
    sentence: 'I will come to the party ___ I finish my homework first.',
    options: ['if', 'slowly', 'happy', 'under'],
    correctAnswer: 'if',
    wordClass: 'conjunction',
    explanation: '"If" is a subordinating conjunction showing a condition.',
  },
  {
    id: 44,
    type: 'identify',
    sentence: 'We can go to the park **or** stay at home.',
    highlightedWord: 'or',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Determiner'],
    correctAnswer: 'Conjunction',
    wordClass: 'conjunction',
    explanation: '"Or" is a coordinating conjunction offering a choice.',
  },

  // ── DETERMINERS ────────────────────────────────────────
  {
    id: 45,
    type: 'identify',
    sentence: '**The** children played in the park.',
    highlightedWord: 'The',
    options: ['Determiner', 'Noun', 'Pronoun', 'Adjective'],
    correctAnswer: 'Determiner',
    wordClass: 'determiner',
    explanation: '"The" is a determiner (definite article) introducing the noun "children".',
  },
  {
    id: 46,
    type: 'identify',
    sentence: '**Some** people prefer tea over coffee.',
    highlightedWord: 'Some',
    options: ['Determiner', 'Pronoun', 'Adjective', 'Adverb'],
    correctAnswer: 'Determiner',
    wordClass: 'determiner',
    explanation: '"Some" is a determiner — it tells us about the quantity of the noun "people".',
  },
  {
    id: 47,
    type: 'identify',
    sentence: '**Every** student must complete the task.',
    highlightedWord: 'Every',
    options: ['Determiner', 'Adjective', 'Pronoun', 'Adverb'],
    correctAnswer: 'Determiner',
    wordClass: 'determiner',
    explanation: '"Every" is a determiner specifying which students (all of them).',
  },
  {
    id: 48,
    type: 'classify',
    sentence: 'Which of these words is a determiner?',
    options: ['an', 'slowly', 'jumped', 'happy'],
    correctAnswer: 'an',
    wordClass: 'determiner',
    explanation: '"An" is a determiner (indefinite article) used before nouns starting with a vowel sound.',
  },
  {
    id: 49,
    type: 'fill-blank',
    sentence: '___ dog in the garden belongs to our neighbour.',
    options: ['That', 'Quickly', 'Running', 'Behind'],
    correctAnswer: 'That',
    wordClass: 'determiner',
    explanation: '"That" is a determiner pointing to a specific dog.',
  },
  {
    id: 50,
    type: 'identify',
    sentence: 'I ate **three** biscuits after lunch.',
    highlightedWord: 'three',
    options: ['Determiner', 'Noun', 'Adjective', 'Adverb'],
    correctAnswer: 'Determiner',
    wordClass: 'determiner',
    explanation: '"Three" is a determiner (number) telling us how many biscuits.',
  },

  // ── MIXED / TRICKY QUESTIONS ───────────────────────────
  {
    id: 51,
    type: 'identify',
    sentence: 'The old man sat **quietly** on the bench.',
    highlightedWord: 'quietly',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Quietly" is an adverb describing how the man sat.',
  },
  {
    id: 52,
    type: 'identify',
    sentence: 'The children **have** finished their work.',
    highlightedWord: 'have',
    options: ['Verb', 'Noun', 'Pronoun', 'Determiner'],
    correctAnswer: 'Verb',
    wordClass: 'verb',
    explanation: '"Have" is an auxiliary verb helping to form the present perfect tense.',
  },
  {
    id: 53,
    type: 'identify',
    sentence: '**Those** shoes are far too expensive.',
    highlightedWord: 'Those',
    options: ['Determiner', 'Pronoun', 'Adjective', 'Noun'],
    correctAnswer: 'Determiner',
    wordClass: 'determiner',
    explanation: '"Those" is a determiner specifying which shoes.',
  },
  {
    id: 54,
    type: 'identify',
    sentence: 'We drove **across** the bridge at sunset.',
    highlightedWord: 'across',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Verb'],
    correctAnswer: 'Preposition',
    wordClass: 'preposition',
    explanation: '"Across" is a preposition showing direction.',
  },
  {
    id: 55,
    type: 'identify',
    sentence: 'The weather was **extremely** cold yesterday.',
    highlightedWord: 'extremely',
    options: ['Adverb', 'Adjective', 'Noun', 'Verb'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Extremely" is an adverb modifying the adjective "cold".',
  },
  {
    id: 56,
    type: 'identify',
    sentence: '**We** enjoyed the trip to the seaside.',
    highlightedWord: 'We',
    options: ['Pronoun', 'Determiner', 'Noun', 'Conjunction'],
    correctAnswer: 'Pronoun',
    wordClass: 'pronoun',
    explanation: '"We" is a personal pronoun standing in place of specific people.',
  },
  {
    id: 57,
    type: 'classify',
    sentence: 'Which word class does "while" belong to in: "She read while he cooked"?',
    options: ['Conjunction', 'Preposition', 'Adverb', 'Noun'],
    correctAnswer: 'Conjunction',
    wordClass: 'conjunction',
    explanation: '"While" is a subordinating conjunction joining two clauses and showing they happen at the same time.',
  },
  {
    id: 58,
    type: 'identify',
    sentence: 'The **ancient** castle stood on top of the hill.',
    highlightedWord: 'ancient',
    options: ['Adjective', 'Noun', 'Adverb', 'Verb'],
    correctAnswer: 'Adjective',
    wordClass: 'adjective',
    explanation: '"Ancient" is an adjective describing the age of the castle.',
  },
  {
    id: 59,
    type: 'identify',
    sentence: 'He could **not** believe what had happened.',
    highlightedWord: 'not',
    options: ['Adverb', 'Conjunction', 'Preposition', 'Determiner'],
    correctAnswer: 'Adverb',
    wordClass: 'adverb',
    explanation: '"Not" is an adverb — it modifies the verb "believe" by making it negative.',
  },
  {
    id: 60,
    type: 'identify',
    sentence: 'The dog lay **inside** its kennel all day.',
    highlightedWord: 'inside',
    options: ['Preposition', 'Adverb', 'Noun', 'Adjective'],
    correctAnswer: 'Preposition',
    wordClass: 'preposition',
    explanation: '"Inside" is a preposition showing the position of the dog relative to the kennel.',
  },
];
